apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: meuapp
  name: meuapp
spec:
  replicas: 6
  selector:
    matchLabels:
      app: meuapp
  template:
    metadata:
      labels:
        app: meuapp
    spec:
      containers:
      - image: herijr/meuapp
        imagePullPolicy: Always
        name: meuapp
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: meuapp
  name: meuapp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: meuapp
  type: ClusterIP